# Generated by Django 6.0.5 on 2026-06-04 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hazard',
            name='alert_level',
            field=models.CharField(choices=[('green', 'Green (Low Risk)'), ('yellow', 'Yellow (Moderate Risk)'), ('amber', 'Amber (Elevated Risk)'), ('orange', 'Orange (High Risk)'), ('red', 'Red (Critical Risk)')], default='green', max_length=20),
        ),
    ]
